const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');
const base=process.env.STORY_URL||'http://127.0.0.1:3107';const results=[];const settle=async p=>{let previous=NaN,stable=0;for(let i=0;i<50;i++){await p.waitForTimeout(100);const y=await p.evaluate(()=>scrollY);stable=Math.abs(previous-y)<1?stable+1:0;previous=y;if(stable>=3)return;}throw Error('Scroll did not settle');};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{
for(const [width,height,motion,js] of [[1440,900,'no-preference',true],[1280,720,'no-preference',true],[1180,757,'no-preference',true],[1000,720,'no-preference',true],[1180,650,'no-preference',true],[390,844,'no-preference',true],[320,740,'no-preference',true],[768,1024,'no-preference',true],[1440,900,'reduce',true],[390,844,'reduce',true],[1440,900,'no-preference',false]].filter((_,i)=>process.env.STORY_CASE===undefined||i===Number(process.env.STORY_CASE))){
const p=await b.newPage({viewport:{width,height},reducedMotion:motion,javaScriptEnabled:js});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await p.goto(base,{waitUntil:'networkidle',timeout:120000});await settle(p);
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow');const brand=await p.getByRole('link',{name:'ClearSig home',exact:true}).boundingBox(),menu=await p.getByRole('button',{name:'Menu',exact:true}).boundingBox();assert(brand.x+brand.width<menu.x,'header brand clears menu');const enhanced=width>=1000&&height>=720&&motion!=='reduce'&&js;assert.equal(await p.locator('#approval').getAttribute('data-enhanced'),String(enhanced));
for(const [i,id]of ['request','rules','people','rules','request'].entries()){await p.locator('#story-'+id).evaluate(e=>e.scrollIntoView({behavior:'instant',block:'start'}));await settle(p);if(js){assert.equal(await p.locator('nav[aria-label="Approval story navigation"] a[aria-current="step"]').getAttribute('href'),'#story-'+id);if(enhanced){const box=await p.locator('[class*="ApprovalStory_stage_"]').boundingBox();assert(box.y>=90&&box.y<140,'stage pinned '+box.y);if(id==='people'){const owner=await p.locator('[class*="ApprovalStory_stage_"] [class*="owners_"]').boundingBox(),hud=await p.locator('[aria-label="Approval story navigation"]').boundingBox();assert(owner.y+owner.height<hud.y,'owner panel clears navigation');}}}}
if(js){await p.locator('#story-rules button').click();assert.match(await p.locator('[role="status"]').first().textContent(),/Policy failed/);assert.equal(await p.locator('#story-people button').isDisabled(),true);await p.locator('#story-rules button').click();await p.locator('#story-people button').click();assert.match(await p.locator('[role="status"]').first().textContent(),/Two demo approvals/);await p.locator('#story-people button').click();assert.match(await p.locator('[role="status"]').first().textContent(),/One demo approval/);
await p.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await p.getByRole('dialog').isVisible(),true);const before=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,700);await settle(p);assert.equal(await p.evaluate(()=>scrollY),before,'menu scroll lock');for(let n=0;n<18;n++){await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)),true,'focus trap');}await p.keyboard.press('Escape');await settle(p);assert.equal(await p.getByRole('dialog').isVisible(),false);assert.equal(await p.getByRole('button',{name:'Menu',exact:true}).evaluate(e=>e===document.activeElement),true,'focus restore');
await p.getByRole('button',{name:'Menu',exact:true}).click();await p.goBack();await settle(p);assert.equal(await p.getByRole('dialog').isVisible(),false);await p.goForward();await settle(p);assert.equal(await p.getByRole('dialog').isVisible(),true);await p.getByRole('dialog').getByRole('link',{name:'Questions & resources'}).click();await settle(p);assert.equal(await p.getByRole('dialog').isVisible(),false);assert.equal(new URL(p.url()).hash,'#resources');
await p.locator('nav[aria-label="Approval story navigation"]').getByRole('link',{name:'Skip story'}).click();await settle(p);assert.equal(new URL(p.url()).hash,'#products');assert((await p.locator('#products').boundingBox()).y<180,'skip reaches products');
await p.goto(base+'/#story-rules',{waitUntil:'networkidle'});await settle(p);assert(Math.abs((await p.locator('#story-rules').boundingBox()).y-112)<15,'deep link');await p.reload({waitUntil:'networkidle'});await settle(p);assert(Math.abs((await p.locator('#story-rules').boundingBox()).y-112)<15,'refresh');
}else{assert.equal(await p.getByRole('button',{name:'Menu',exact:true}).isDisabled(),true);assert.equal(await p.locator('#story-rules button').isDisabled(),true);assert.equal(await p.locator('#story-request h3').isVisible(),true);}
if(width<1000){await p.locator('#story-people button').evaluate(e=>e.scrollIntoView({behavior:'instant',block:'center'}));await settle(p);const button=await p.locator('#story-people button').boundingBox(),hud=await p.locator('[aria-label="Approval story navigation"]').boundingBox();assert(button.y+button.height<hud.y,'mobile approval CTA clearance');await p.locator('footer').getByRole('link',{name:'Back to the beginning'}).focus();await settle(p);const end=await p.locator('footer').getByRole('link',{name:'Back to the beginning'}).boundingBox();assert(end.y+end.height<hud.y,'mobile footer clearance');}assert.deepEqual(errors,[]);results.push({width,height,motion,js,enhanced,status:'passed'});await p.close();console.log(results.at(-1));}
}finally{await b.close();fs.writeFileSync(process.env.STORY_REPORT||'/tmp/clearsig-story-browser-results.json',JSON.stringify(results,null,2))}})().catch(e=>{console.error(e);process.exitCode=1});
