import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Keypair,SystemProgram,TransactionMessage,VersionedTransaction} from '@solana/web3.js';
import bs58 from 'bs58';
import {WalletContext} from './secureBoundary.fixture';
import {useSecureOperation,SecureRecoveryNotice} from '@/features/secure/infrastructure/useSecureOperation';
const signer=Keypair.fromSeed(new Uint8Array(32).fill(4));
const other=Keypair.fromSeed(new Uint8Array(32).fill(5));
window.fixtureStats={wallet:0,send:0,outcome:'idle',failure:false,known:false};
window.fixtureConnection={rpcEndpoint:'http://fixture.invalid',getGenesisHash:async()=>'fixture-genesis',isBlockhashValid:async()=>({value:true}),sendRawTransaction:async bytes=>{window.fixtureStats.send++;if(window.fixtureStats.failure)throw new Error('Synthetic connection loss');return bs58.encode(VersionedTransaction.deserialize(bytes).signatures[0]);},confirmTransaction:async()=>({value:{err:null}}),getSignatureStatuses:async signatures=>({value:signatures.map(()=>window.fixtureStats.known?{confirmationStatus:'confirmed',err:null}:null)})};
function Form(){const [amount,setAmount]=useState('1');const secure=useSecureOperation(amount);async function begin(){try{await secure.run(`Synthetic transfer ${amount}`,async operation=>{window.fixtureStats.outcome='preparing';await new Promise(r=>{window.finishPreparation=r});operation.assertCurrent();const transaction=new VersionedTransaction(new TransactionMessage({payerKey:signer.publicKey,recentBlockhash:other.publicKey.toBase58(),instructions:[SystemProgram.transfer({fromPubkey:signer.publicKey,toPubkey:other.publicKey,lamports:BigInt(amount)})]}).compileToV0Message());const signed=await operation.signTransaction(transaction);const sig=await operation.connection.sendRawTransaction(signed.serialize());await operation.connection.confirmTransaction(sig)});window.fixtureStats.outcome='done'}catch(e){window.fixtureStats.outcome=e.message}}
return <><label>Amount<input aria-label="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button onClick={begin}>Prepare</button><SecureRecoveryNotice recovery={secure}/></>}
function App(){const [account,setAccount]=useState(false);const [visible,setVisible]=useState(true);return <WalletContext.Provider value={{connected:true,sessionSubject:'synthetic',publicKey:account?other.publicKey:signer.publicKey,dynamicPublicKey:account?other.publicKey:signer.publicKey,isLedger:false,signTransaction:async tx=>{window.fixtureStats.wallet++;tx.sign([signer]);return tx}}}><h1>Synthetic Secure lifecycle</h1><button onClick={()=>setAccount(v=>!v)}>Switch account</button><button onClick={()=>setVisible(v=>!v)}>Toggle page</button>{visible&&<Form/>}</WalletContext.Provider>};createRoot(document.getElementById('root')).render(<App/>);
