pub fn test_config(database_url: &str) -> rust_settlement::config::AppConfig {
    rust_settlement::config::AppConfig {
        bind_addr: String::new(),
        database_url: database_url.to_string(),
        auth: rust_settlement::auth::DynamicAuthConfig::new(
            "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
            "http://localhost:3000",
        )
        .unwrap(),
        paystack_secret_key: "test-only-not-a-credential".to_string(),
        paystack_base_url: "https://unused.invalid".to_string(),
        paystack_webhook_secret: String::new(),
        kora_secret_key: String::new(),
        kora_base_url: "https://unused.invalid".to_string(),
        kora_webhook_secret: String::new(),
        ramp_payment_provider: "paystack".to_string(),
        worker_poll_interval_ms: 1,
        treasury_signer_backend: String::new(),
        evm_rpc_url: String::new(),
        treasury_evm_private_key: String::new(),
        treasury_evm_address: String::new(),
        solana_rpc_url: String::new(),
        treasury_sol_keypair_base58: String::new(),
        treasury_sol_keypair_path: String::new(),
        treasury_sol_address: String::new(),
        bitcoin_network: String::new(),
        bitcoin_esplora_url: String::new(),
        treasury_btc_private_key_wif: String::new(),
        treasury_btc_address: String::new(),
        bitcoin_fee_sats_per_vbyte: 1,
        zcash_rpc_url: String::new(),
        zcash_rpc_user: String::new(),
        zcash_rpc_password: String::new(),
        treasury_zec_address: String::new(),
        enable_treasury_liquidity_check: false,
        onramp_max_usd_cents: 1000,
        ramp_frontend_callback_url: None,
    }
}
